using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Menu : MonoBehaviour
{
    public void Problem1() 
    {
        SceneManager.LoadScene("Problem-1");
    }

    public void Problem2()
    {
        SceneManager.LoadScene("Problem-2");
    }

    public void Problem3()
    {
        SceneManager.LoadScene("Problem-3");
    }

    public void Problem4()
    {
        SceneManager.LoadScene("Problem-4");
    }

    public void Problem5()
    {
        SceneManager.LoadScene("Problem-5");
    }

    public void Problem6()
    {
        SceneManager.LoadScene("Problem-6");
    }

    public void Problem7()
    {
        SceneManager.LoadScene("Problem-7");
    }

    public void Problem8()
    {
        SceneManager.LoadScene("Problem-8");
    }

    public void Problem9()
    {
        SceneManager.LoadScene("Problem-9");
    }

    public void Problem10()
    {
        SceneManager.LoadScene("Problem-10");
    }

    private void Update()
	{
        if (Input.GetKeyDown(KeyCode.Escape)) 
        {
            SceneManager.LoadScene("Problem-10");
        }
	}
}
